### ISSUE TITLE
If you can show you more details of the application of such as can record a video

### ISSUE THREAD

**Issue by guoyoujin** [LyndonChin/AndroidGlitterView#1]
If you can show you more details of the application of such as can record a video

**Comment by liangfeidotme** [comment]
@guoyoujin Thank you for your consideration. Do you mean record the screen to video ?

**Comment by guoyoujin** [comment]
@LyndonChin Yes, it can be more intuitive shows you the functions, recording screen experience have you had

**Comment by guoyoujin** [comment]
@LyndonChin Ok, I have seen your demo presentation, is very good, thank you
